action_id: trunk-single-player-auto-upgrade
date: 2026-03-04 01:48:18
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1772588898
full_timestamp:
  nanos: 277138000
  seconds: 1772588898
trunk_version: 1.25.0
