action_id: trunk-cache-prune
date: 2026-03-04 00:48:17
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1772585297
full_timestamp:
  nanos: 797014000
  seconds: 1772585297
trunk_version: 1.25.0
