action_id: trunk-cache-prune
date: 2026-03-03 22:22:48
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1772576568
full_timestamp:
  nanos: 253944000
  seconds: 1772576568
trunk_version: 1.25.0
