action_id: trunk-cache-prune
date: 2026-03-03 23:22:50
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1772580170
full_timestamp:
  nanos: 169744000
  seconds: 1772580170
trunk_version: 1.25.0
