@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\Firash\AppData\Local\trunk\tools\osv-scanner\2.3.3-26eb5d87a2b1eadff549407f90c7517d;C:\Users\Firash\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Firash\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
