@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\Firash\AppData\Local\trunk\tools\trufflehog\3.93.6-cf1a5ee81c4cba891cb0c9398625fa18;C:\Users\Firash\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Firash\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
