action_id: trunk-share-with-everyone
date: 2026-03-04 00:53:31
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-share-with-everyone\r\n"
  err: ""
timestamp: 1772585611
full_timestamp:
  nanos: 163567000
  seconds: 1772585611
trunk_version: 1.25.0
action_output:
  notifications_to_delete:
    - trunk-share-with-everyone
